# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=260, null=True, verbose_name='答案内容')),
                ('val', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '答案表',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='班级名')),
            ],
            options={
                'verbose_name': '班级表',
            },
        ),
        migrations.CreateModel(
            name='One_choice',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='选项名')),
                ('score', models.IntegerField(verbose_name='选项对应的分值')),
            ],
            options={
                'verbose_name': '单选题选项表',
            },
        ),
        migrations.CreateModel(
            name='Quesion',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('quesion', models.CharField(max_length=100, verbose_name='问题名')),
                ('tp', models.IntegerField(choices=[(1, '打分'), (2, '单选'), (3, '评价')])),
            ],
            options={
                'verbose_name': '问题表',
            },
        ),
        migrations.CreateModel(
            name='Questionary',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '问卷表',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30, verbose_name='学生名')),
                ('pwd', models.CharField(max_length=32)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Grade', verbose_name='学生与班级关系')),
            ],
            options={
                'verbose_name': '学生表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '员工表',
            },
        ),
        migrations.AddField(
            model_name='questionary',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo'),
        ),
        migrations.AddField(
            model_name='questionary',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Grade', verbose_name='和班级对应关系'),
        ),
        migrations.AddField(
            model_name='one_choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Quesion'),
        ),
        migrations.AddField(
            model_name='answer',
            name='one_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.One_choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='quesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Quesion'),
        ),
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Student'),
        ),
    ]
