# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesion',
            name='naire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.Questionary'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='创建者'),
        ),
    ]
