# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171206_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one_choice',
            name='score',
            field=models.IntegerField(default=True, null=True, verbose_name='选项对应的分值'),
        ),
    ]
